apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1  # Specifies the number of instances
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: webserver
    spec:
      contaners:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
